version: '3.7'
services:
  php-fpm:
    ports: [ '8122:80' ]
    working_dir: /app
    depends_on:
      - postgres
    build:
      context: .
      target: php_dev
      dockerfile: Dockerfile
    entrypoint: symfony local:server:start --no-tls --port=80
    volumes:
      - .:/app:cached
      - ./bin:/app/bin:consistent
      - ./config:/app/config:consistent
      - ./public:/app/public:consistent
      - ./src:/app/src:consistent
      - ./var:/app/var:consistent
      - ${HOME}/.config/gcloud:/root/.config/gcloud:cached
  postgres:
    image: bitnami/postgresql:12
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
  phpstan:
    build:
      dockerfile: .docker/phpstan/Dockerfile
      context: .
    volumes:
      - .:/app:cached
      - ./bin:/app/bin:consistent
      - ./config:/app/config:consistent
      - ./public:/app/public:consistent
      - ./src:/app/src:consistent
      - ./var:/app/var:consistent
      - ${HOME}/.config/gcloud:/root/.config/gcloud:cached
  phpcs:
    build:
      dockerfile: .docker/phpcs/Dockerfile
      context: .
    volumes:
      - .:/app:cached
      - ./bin:/app/bin:consistent
      - ./config:/app/config:consistent
      - ./public:/app/public:consistent
      - ./src:/app/src:consistent
      - ./var:/app/var:consistent
      - ${HOME}/.config/gcloud:/root/.config/gcloud:cached
